pipeline {
    agent any

    environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
	}
    stages {
        stage('Docker Login') {
            steps {
              sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Build & push Dockerfile') {
            steps {
              sh """
              cd comingsoon/
              ansible-playbook playbook.yml
              """
            }
        }
        stage('Delete Cluster') {
            steps {
                script {
                    sh "minikube delete -p comingsoon-cluster"
                    sleep(time: 180, unit: "SECONDS")
                }
            }
        }
        
        stage('Create Cluster') {
            steps {
                script {
                    sh """
                    minikube start -p comingsoon-cluster --nodes-min=2
                    kubectl update-kubeconfig --name comingsoon-cluster
                    """
                }
            }
        }
        
        stage('Create Namespace') {
            steps {
                script {
                    sh "kubectl create namespace comingsoon"
                }
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    sh """
                    cd Kubernetes/comingsoon/k8s
                    kubectl apply -f deployment.yaml -n comingsoon
                    kubectl apply -f services.yaml -n comingsoon
                    """
                }
            }
        }
    }
}

