- name: "Build container with ansible"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop comingsoon-page1con

  - name: remove stopped container

    command: docker rm comingsoon-page1con

  - name: remove used image

    command: docker rmi imas10/comingsoon-page-kuber

  - name: build docker image from dockerfile

    command: docker build -t imas10/comingsoon-page-kuber .

  - name: tag the docker image
  
    command: docker tag comingsoon-page-kuber imas10/comingsoon-page-kuber:latest

  - name: push image to dockerhub
    command: docker push imas10/comingsoon-page-kuber:latest
