apiVersion: apps/v1 
kind: Deployment
metadata:
  name: comingsoon-page-img-deployment 
  namespace: comingsoon
spec:
  selector:
    matchLabels:
      app: comingsoon-page
  replicas: 4
  template:
    metadata:
      labels:
        app: comingsoon-page
    spec:
      containers:
      - name: comingsoon-page
        image: imas10/comingsoon-page-kuber:0.0.01
        ports:
        - containerPort: 80
